database:
  database: purrfectbitesdb
  username: k8lobova
  password: k8lobova
  host: rc1b-5o05n7l3388upa0u.mdb.yandexcloud.net
  port: 6432
  sslmode: verify-full
  target_session_attrs: read-write

api:
  key: 5b3ce3597851110001cf624860bbe2ce295c433185dd45a4f3e1ae18


